- --site-lat
- '-22.9855235'
- --site-lon
- '-67.7403087'
- --site-alt
- '5610'
- --site-name
- Cerro-Chajnantor
- --telescope
- FYST
- --start
- '2025-06-01 00:00:00'
- --stop
- '2025-06-04 23:00:00'
- --patch-coord
- C
- --patch
- COSMOSRECT_01_06,1,148,3,152,1
- --el-min-deg
- '40'
- --el-max-deg
- '70'
- --sun-avoidance-angle-deg
- '35'
- --ces-max-time-s
- '900'
- --gap-s
- '0.0'
- --gap-small-s
- '0.0'
- --fp-radius-deg
- '0.0'
- --no-partial-scans
- --out
- schedule_COSMOSRECT_01_06.txt
