- --site-lat
- '-22.9855235'
- --site-lon
- '-67.7403087'
- --site-alt
- '5610'
- --site-name
- Cerro-Chajnantor
- --telescope
- FYST
- --patch-coord
- C
- --start
- '2031-06-30 00:00:00'
- --stop
- '2031-06-30 23:59:59'
- --patch
- COSMOS_2031_06_30,1,150,2,2.0
- --el-min-deg
- '40'
- --el-max-deg
- '65'
- --sun-avoidance-angle-deg
- '35'
- --ces-max-time-s
- '300'
- --fp-radius-deg
- '0.0'
- --gap-s
- '0.0'
- --gap-small-s
- '0.0'
- --no-partial-scans
- --out
- ./gen_schedules/schedule_COSMOS_2031_06_30.txt
